Repository LiberTEM/LiberTEM, pull requests merged in 2020-05, with the labels that each got.

#770 Acknowledge John Gaida
  packaging/contributors.json
Labels: docs

#771 Update pytest-asyncio
  test_requirements.txt
Labels: infra

#773 Update README.rst with Norpix SEQ
  README.rst
Labels: docs

#774 Tweak bookmarking feature
  client/package-lock.json
  client/src/browser/components/PathBar.tsx
  client/src/config/helpers.ts
  client/src/config/sagas.ts
  docs/source/images/use/star.png
  docs/source/usage.rst
  src/libertem/web/client/asset-manifest.json
  src/libertem/web/client/index.html
  src/libertem/web/client/precache-manifest.2c16b5cc6e6de6d8ec1533faee7095e6.js
  src/libertem/web/client/service-worker.js
  src/libertem/web/client/static/js/main.1a3ad800.chunk.js
  src/libertem/web/client/static/js/main.1a3ad800.chunk.js.map
  src/libertem/web/client/static/js/main.72e2a431.chunk.js
  src/libertem/web/client/static/js/main.72e2a431.chunk.js.map
Labels: GUI

#784 Add simple docstring to `get_tiling_preferences`
  src/libertem/udf/base.py
Labels: docs

#788 Support for running multiple UDFs simultaneously
  docs/source/changelog/features/multi_udf_runner.rst
  src/libertem/analysis/clust.py
  src/libertem/api.py
  src/libertem/io/dataset/base/tiling.py
  src/libertem/udf/base.py
  src/libertem/web/jobs.py
  tests/io/test_tiling_negotiation.py
  tests/udf/test_multi_udf.py
  tests/udf/test_udf_runner.py
Labels: Python API, UDFs

#785 Add example notebook with an introduction to UDFs
  examples/Introduction to UDFs.ipynb
Labels: docs
