Repository LiberTEM/LiberTEM, pull requests merged in 2020-01, with the labels that each got.

#537 Disable ROI selector if the current mode is PICK
  client/src/analysis/components/AnalysisLayoutThreeCol.tsx
  client/src/analysis/components/DefaultFrameView.tsx
  docs/source/changelog/bugfix/fix_pick_roi_interaction.rst
  src/libertem/web/client/asset-manifest.json
  src/libertem/web/client/index.html
  src/libertem/web/client/precache-manifest.8ec0d0467175fd9e99dc19da8e35519e.js
  src/libertem/web/client/service-worker.js
  src/libertem/web/client/static/js/main.57be1889.chunk.js
  src/libertem/web/client/static/js/main.57be1889.chunk.js.map
  src/libertem/web/client/static/js/main.aa6cb99b.chunk.js
  src/libertem/web/client/static/js/main.aa6cb99b.chunk.js.map
Labels: GUI, bug

#538 Record coverage for numba njit functions
  .travis.yml
  setup.cfg
  tests/io/test_k2is_uint12.py
  tests/udf/test_blobfinder.py
  tox.ini
Labels: infra

#544 Configure codeclimate maintainability rules
  .codeclimate.yml
Labels: infra

#563 Fix mangled data in RadialFourierAnalysis from recent change to UDF back-end
  src/libertem/analysis/radialfourier.py
  tests/test_analysis_radialfourier.py
Labels: bug

#560 More on GSoC 2020
  docs/source/gsoc.rst
Labels: docs
