Repository LiberTEM/LiberTEM, pull requests merged in 2020-06, with the labels that each got.

#821 Make sub level headlines to remove from left column TOC
  docs/source/concepts.rst
Labels: docs

#825 Add JOSS badge to README
  README.rst
Labels: docs

#829 Make test success not depend on numerical noise close to zero
  src/libertem/analysis/fullmatch.py
Labels: bug

#822 Test on ipyparallel
  .travis.yml
  conftest.py
  packaging/docker/Dockerfile
  packaging/docker/docker-compose.yml
  packaging/docker/requirements.txt
  tests/test_ipython.py
Labels: QA

#830 Follow-up of the move to travis-ci.com: fix badge link, re-order
  README.rst
Labels: docs

#832 SER: don't use emifile argument anymore
  src/libertem/io/dataset/ser.py
Labels: bug, file formats and I/O

#840 Add a warning if a MIB data set is saved in an inefficient way
  src/libertem/io/dataset/mib.py
  tests/io/datasets/test_mib.py
Labels: QA, UX/DX, file formats and I/O

#841 Add a note about browsers we test on
  docs/source/usage.rst
Labels: docs
