Repository LiberTEM/LiberTEM, pull requests merged in 2020-03, with the labels that each got.

#661 Comment out index URLs from override_requirements
  override_requirements.txt
Labels: infra

#672 Perform calculation in float64
  src/libertem/udf/stddev.py
Labels: bug

#650 Added citation of dataset used
  docs/source/references-libertem.bib
  docs/source/usage.rst
Labels: GSOC, docs

#670 Modifying the documentation
  docs/source/changelog/documentation/modify_doc.rst
  docs/source/concepts.rst
  docs/source/index.rst
  docs/source/sample_datasets.rst
  docs/source/udf/profiling.rst
  packaging/creators.json
Labels: GSOC, docs

#683 Add pytest-xdist
  test_requirements.txt
  tox.ini
Labels: infra

#684 Limit to distributed < 2.9
  prototypes/reproducers/test-dask-remote.ipynb
  setup.py
Labels: WIP, bug
