Repository LiberTEM/LiberTEM, pull requests merged in 2020-04, with the labels that each got.

#711 Fixing typo
  src/libertem/io/dataset/base/dataset.py
Labels: GSOC

#712 Add link to GitHub PR video
  docs/source/contributing.rst
Labels: docs

#737 Pin pytest-asyncio to <0.11
  test_requirements.txt
Labels: bug, infra

#744 Exclude flaky tests
  docs/source/releasing.rst
  setup.cfg
  tests/server/test_browse.py
  tests/server/test_cancel.py
  tests/server/test_dataset.py
  tests/server/test_download.py
  tests/server/test_ds_detect.py
  tests/server/test_job.py
  tests/server/test_startup.py
  tests/server/test_state.py
Labels: infra

#746 Fix remote file opening in SER
  src/libertem/io/dataset/ser.py
Labels: bug, file formats and I/O
