Repository LiberTEM/LiberTEM, pull requests merged in 2020-11, with the labels that each got.

#565 Set up CI with Azure Pipelines
  .dockerignore
  .travis.yml
  README.rst
  appveyor.yml
  azure-pipelines.yml
  conftest.py
  packaging/docker/Dockerfile
  packaging/docker/docker-compose.yml
  scripts/deploy_docs
  scripts/release
  scripts/requirements.txt
  src/libertem/executor/base.py
  src/libertem/executor/dask.py
  src/libertem/utils/async_utils.py
  test_requirements.txt
  tests/template/test_ring_template.py
  tox.ini
Labels: AAA-Priority, QA, infra

#908 Update azure pipelines
  azure-pipelines-data.yml
  azure-pipelines.yml
  conftest.py
  tests/aio_utils.py
  tests/server/test_browse.py
  tests/server/test_cancel.py
  tests/server/test_copy.py
  tests/server/test_download.py
  tests/server/test_ds_detect.py
  tests/server/test_job.py
  tests/server/test_startup.py
  tests/template/test_com_template.py
  tests/template/test_disk_template.py
  tests/template/test_fem_template.py
  tests/template/test_fft_template.py
  tests/template/test_pick_template.py
  tests/template/test_point_template.py
  tests/template/test_radial_fourier_template.py
  tests/template/test_ring_template.py
  tests/template/test_sd_template.py
  tests/template/test_sum_template.py
  tests/template/test_sumsig_template.py
Labels: infra

#909 More azure pipeline updates
  azure-pipelines.yml
  conftest.py
  scripts/release
  tests/server/test_dataset.py
  tests/server/test_startup.py
  tests/template/test_clust_template.py
  tests/template/test_com_template.py
  tests/template/test_disk_template.py
  tests/template/test_fem_template.py
  tests/template/test_fft_template.py
  tests/template/test_pick_template.py
  tests/template/test_point_template.py
  tests/template/test_radial_fourier_template.py
  tests/template/test_ring_template.py
  tests/template/test_sd_template.py
  tests/template/test_sum_template.py
  tests/template/test_sumsig_template.py
Labels: infra

#913 Make sure the damaged data is different from the corrected
  tests/corrections/test_detector.py
Labels: QA, bug
