Repository LiberTEM/LiberTEM, pull requests merged in 2021-04, with the labels that each got.

#1009 Speed up `test_comparison{,_roi}` for K2IS and FRMS6
  tests/io/datasets/test_frms6.py
  tests/io/datasets/test_k2is.py
Labels: QA, enhancement

#1017 Fix initial pick position
  client/package-lock.json
  client/src/cluster/components/LocalConnectionForm.tsx
  client/src/compoundAnalysis/components/DefaultFrameView.tsx
  client/src/compoundAnalysis/components/FFTFrameView.tsx
  src/libertem/web/client/asset-manifest.json
  src/libertem/web/client/index.html
  src/libertem/web/client/precache-manifest.9ba7b9b5c282356dfca2714fa5348557.js
  src/libertem/web/client/service-worker.js
  src/libertem/web/client/static/js/main.73a30785.chunk.js
  src/libertem/web/client/static/js/main.73a30785.chunk.js.map
  src/libertem/web/client/static/js/main.b17da934.chunk.js
  src/libertem/web/client/static/js/main.b17da934.chunk.js.map
Labels: GUI, bug

#1021 Fix headline hierarchy
  docs/source/tips.rst
Labels: bug, docs

#1022 Some small doc tweaks
  src/libertem/analysis/base.py
  src/libertem/api.py
Labels: docs

#1023 Bugfix for COM analysis template
  docs/source/changelog/bugfix/com.rst
  src/libertem/analysis/com.py
Labels: bug
