Repository LiberTEM/LiberTEM, pull requests merged in 2021-02, with the labels that each got.

#945 Fix logic bug in GPU selector
  client/src/cluster/components/GPUSelector.tsx
  src/libertem/web/client/asset-manifest.json
  src/libertem/web/client/index.html
  src/libertem/web/client/precache-manifest.280eecafc9b12d01009077d167bbd121.js
  src/libertem/web/client/service-worker.js
  src/libertem/web/client/static/js/main.3676db7a.chunk.js
  src/libertem/web/client/static/js/main.3676db7a.chunk.js.map
  src/libertem/web/client/static/js/main.e87cdaea.chunk.js
  src/libertem/web/client/static/js/main.e87cdaea.chunk.js.map
Labels: bug

#952 Handle an empty DVD drive on Windows gracefully
  src/libertem/io/fs.py
Labels: GUI, UX/DX, windows

#957 Better error message when trying to open 2D HDF5 files
  conftest.py
  src/libertem/common/shape.py
  src/libertem/io/dataset/hdf5.py
  tests/common/test_shape.py
  tests/io/datasets/test_hdf5.py
Labels: UX/DX, file formats and I/O

#975 Use `python -m pip`
  README.rst
  docs/source/contributing.rst
  docs/source/dev/setup.rst
  docs/source/install.rst
  docs/source/releasing.rst
  docs/source/tips.rst
  docs/source/udf/profiling.rst
Labels: docs

#977 Finishing touches changelog 0.6.0
  docs/source/changelog.rst
  docs/source/changelog/misc/nothing.rst
  src/libertem/udf/base.py
Labels: docs
