Repository LiberTEM/LiberTEM, pull requests merged in 2023-07, with the labels that each got.

#1454 Pin `scikit-learn` to `<1.3.0` and `dask!=2023.6.1`
  setup.py
Labels: dependencies

#1459 Add changelog entry for point release v0.11.2
  docs/source/changelog.rst
Labels: docs

#1465 Support and test indptr with dtype uint64
  conftest.py
  docs/source/changelog/bugfix/raw_csr_uint64.rst
  src/libertem/io/dataset/raw_csr.py
  tests/io/datasets/test_raw_csr.py
Labels: bug, file formats and I/O
